name: calcium
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=23.1.2
  - tensorflow-gpu=2.0.0
  - tensorflow-estimator=2.0.0
  - tensorboard=2.0.0
  - keras=2.3.1
  - numpy=1.19.2
  - pillow=9.0.1
  - scipy=1.6.2
  - matplotlib=3.5.3
  - h5py=2.10.0
  - scikit-learn=0.20.3
  - pip:
    - PyQt5==5.15.6
    - PyQt5-Qt5==5.15.2
    - PyQt5-sip==12.10.1
    - opencv-python
    - opencv-contrib-python
